// import 'package:client_app/model/product.dart';

// class Myproducts {
//   static List<Product> allProducts =[
//     Product(
//       id: 1,
//       name: "Lenovo s510p", 
//       processor: "Core i5 4th gen", 
//       ram: 8, 
//       storage: 1, 
//       price: 10000,
//       image: "assets/images/laptop.png",
//       storageType: "tb hdd", 
//       screenSize: 15.6, 
//       windows: "windows 10", 
//       battery: "New with warranty", 
//       additionalInfo: "keyboard with warranty", 
//       condition: "Good", 
//       quantity: 1, 
//       category: "laptop", 
//       subCategory: "lenovo"),
//       Product(
//       id: 1,
//       name: "Hp", 
//       processor: "Core i5 4th gen", 
//       ram: 8, 
//       storage: 1, 
//       price: 10000,
//       image: "assets/images/laptop.png",
//       storageType: "tb hdd", 
//       screenSize: 15.6, 
//       windows: "windows 10", 
//       battery: "New with warranty", 
//       additionalInfo: "keyboard with warranty", 
//       condition: "Good", 
//       quantity: 1, 
//       category: "laptop", 
//       subCategory: "lenovo"),
//       Product(
//       id: 1,
//       name: "Lenovo s510p", 
//       processor: "Core i5 4th gen", 
//       ram: 8, 
//       storage: 1, 
//       price: 10000,
//       image: "assets/images/laptop.png",
//       storageType: "tb hdd", 
//       screenSize: 15.6, 
//       windows: "windows 10", 
//       battery: "New with warranty", 
//       additionalInfo: "keyboard with warranty", 
//       condition: "Good", 
//       quantity: 1, 
//       category: "laptop", 
//       subCategory: "lenovo"),
//       Product(
//       id: 1,
//       name: "Lenovo s510p", 
//       processor: "Core i5 4th gen", 
//       ram: 8, 
//       storage: 1, 
//       price: 10000,
//       image: "assets/images/laptop.png",
//       storageType: "tb hdd", 
//       screenSize: 15.6, 
//       windows: "windows 10", 
//       battery: "New with warranty", 
//       additionalInfo: "keyboard with warranty", 
//       condition: "Good", 
//       quantity: 1, 
//       category: "laptop", 
//       subCategory: "lenovo")
//   ];

// }