// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCeweiwf2MNatMd_w4KJWEfCLiglNS6Yk',
    appId: '1:1042389104380:web:ec993e0cf78d5353174979',
    messagingSenderId: '1042389104380',
    projectId: 'ecomm-3ede3',
    authDomain: 'ecomm-3ede3.firebaseapp.com',
    storageBucket: 'ecomm-3ede3.appspot.com',
    measurementId: 'G-7JZ36S7FEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7VyuKf7iIghtVHD7Sr7LILZHZwKwSbcE',
    appId: '1:1042389104380:android:068aba12914d8b36174979',
    messagingSenderId: '1042389104380',
    projectId: 'ecomm-3ede3',
    storageBucket: 'ecomm-3ede3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8a9Ez-Wpt7yg_EJpC8T0JoedG2KdqfxM',
    appId: '1:1042389104380:ios:522b2b4a1bc82739174979',
    messagingSenderId: '1042389104380',
    projectId: 'ecomm-3ede3',
    storageBucket: 'ecomm-3ede3.appspot.com',
    iosBundleId: 'com.example.clientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8a9Ez-Wpt7yg_EJpC8T0JoedG2KdqfxM',
    appId: '1:1042389104380:ios:522b2b4a1bc82739174979',
    messagingSenderId: '1042389104380',
    projectId: 'ecomm-3ede3',
    storageBucket: 'ecomm-3ede3.appspot.com',
    iosBundleId: 'com.example.clientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2F4sTGcuFC2ne5FmSku4UJ3j-9QEO5sk',
    appId: '1:1042389104380:web:963814b149386716174979',
    messagingSenderId: '1042389104380',
    projectId: 'ecomm-3ede3',
    authDomain: 'ecomm-3ede3.firebaseapp.com',
    storageBucket: 'ecomm-3ede3.appspot.com',
    measurementId: 'G-3L32H2M02D',
  );
}
